begin;

-- This setup intentionally removes all existing application data.
drop trigger if exists on_auth_user_created on auth.users;

drop table if exists public.announcements cascade;
drop table if exists public.jadwal_kelas cascade;
drop table if exists public.tasks cascade;
drop table if exists public.matakuliah cascade;
drop table if exists public.anggota_kelas cascade;
drop table if exists public.kelas cascade;
drop table if exists public.profiles cascade;

drop function if exists public.handle_new_user() cascade;
drop function if exists public.current_user_role() cascade;
drop function if exists public.is_admin() cascade;
drop function if exists public.is_class_member(bigint) cascade;
drop function if exists public.is_class_leader(bigint) cascade;
drop function if exists public.can_manage_class(bigint) cascade;
drop function if exists public.join_class(text) cascade;
drop function if exists public.delete_user_account(uuid) cascade;
drop function if exists public.enforce_academic_role_rules() cascade;
drop function if exists public.enforce_schedule_leader_only() cascade;
drop function if exists public.validate_announcement_course() cascade;
drop function if exists public.set_updated_at() cascade;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text not null default 'Pengguna',
  student_number text,
  role text not null default 'student'
    check (role in ('admin', 'lecturer', 'class_leader', 'student')),
  requested_role text,
  approval_status text not null default 'active'
    check (approval_status in ('active', 'pending', 'rejected')),
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.kelas (
  id bigint generated by default as identity primary key,
  nama_kelas text not null
    check (char_length(trim(nama_kelas)) between 1 and 200),
  kode_kelas text not null unique,
  kode_wakil text unique,
  created_by uuid not null
    references public.profiles(id) on delete cascade,
  is_open boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.anggota_kelas (
  id bigint generated by default as identity primary key,
  kelas_id bigint not null
    references public.kelas(id) on delete cascade,
  user_email text not null,
  role text not null default 'student',
  user_name text not null default 'Pengguna',
  nim text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index class_members_email_idx
  on public.anggota_kelas(kelas_id, lower(user_email));

create table public.matakuliah (
  id bigint generated by default as identity primary key,
  kelas_id bigint
    references public.kelas(id) on delete cascade,
  nama text not null
    check (char_length(trim(nama)) between 1 and 200),
  dosen text not null default '',
  lecturer_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.jadwal_kelas (
  id bigint generated by default as identity primary key,
  kelas_id bigint not null
    references public.kelas(id) on delete cascade,
  matakuliah_id bigint not null
    references public.matakuliah(id) on delete cascade,
  hari text not null,
  jam_mulai time not null,
  jam_selesai time not null,
  ruangan text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jam_selesai > jam_mulai)
);

create table public.tasks (
  id bigint generated by default as identity primary key,
  kelas_id bigint not null
    references public.kelas(id) on delete cascade,
  judul text not null
    check (char_length(trim(judul)) between 1 and 200),
  deskripsi text not null default '',
  created_by uuid not null
    references public.profiles(id) on delete cascade,
  target_role text
    constraint tasks_target_role_must_be_null check (target_role is null),
  waktu_reminder timestamptz not null,
  priority text not null default 'medium'
    check (priority in ('low', 'medium', 'high', 'urgent')),
  status text not null default 'pending'
    check (status in ('pending', 'completed', 'expired')),
  matakuliah_id bigint
    references public.matakuliah(id) on delete set null,
  mata_kuliah text,
  dosen_pengampu text,
  gambar_url text,
  author_email text,
  author_name text,
  author_nim text,
  author_avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.announcements (
  id bigint generated by default as identity primary key,
  title text not null
    check (char_length(trim(title)) between 1 and 200),
  content text not null
    check (char_length(trim(content)) between 1 and 10000),
  created_by uuid not null
    references public.profiles(id) on delete cascade,
  course_id bigint
    constraint announcements_course_id_fkey
    references public.matakuliah(id) on delete set null,
  target_class bigint references public.kelas(id) on delete cascade,
  target_role text
    check (target_role is null or target_role in (
      'admin',
      'lecturer',
      'class_leader',
      'student'
    )),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index profiles_role_idx on public.profiles(role);
create index class_members_class_idx on public.anggota_kelas(kelas_id);
create index courses_class_idx on public.matakuliah(kelas_id);
create index courses_lecturer_idx on public.matakuliah(lecturer_id);
create index schedules_class_day_idx
  on public.jadwal_kelas(kelas_id, hari, jam_mulai);
create unique index schedule_exact_duplicate_idx
  on public.jadwal_kelas(
    kelas_id,
    matakuliah_id,
    hari,
    jam_mulai,
    jam_selesai,
    lower(trim(ruangan))
  );
create index tasks_class_due_idx
  on public.tasks(kelas_id, waktu_reminder);
create index announcements_target_idx
  on public.announcements(target_class, target_role, created_at desc);
create index announcements_course_idx on public.announcements(course_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();
create trigger classes_set_updated_at
  before update on public.kelas
  for each row execute function public.set_updated_at();
create trigger members_set_updated_at
  before update on public.anggota_kelas
  for each row execute function public.set_updated_at();
create trigger courses_set_updated_at
  before update on public.matakuliah
  for each row execute function public.set_updated_at();
create trigger schedules_set_updated_at
  before update on public.jadwal_kelas
  for each row execute function public.set_updated_at();
create trigger tasks_set_updated_at
  before update on public.tasks
  for each row execute function public.set_updated_at();
create trigger announcements_set_updated_at
  before update on public.announcements
  for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    email,
    display_name,
    student_number,
    role,
    requested_role,
    approval_status,
    avatar_url
  )
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'name', 'Pengguna'),
    new.raw_user_meta_data ->> 'nim',
    'student',
    null,
    'active',
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

insert into public.profiles (
  id,
  email,
  display_name,
  student_number,
  role,
  approval_status,
  avatar_url
)
select
  users.id,
  coalesce(users.email, ''),
  coalesce(users.raw_user_meta_data ->> 'name', 'Pengguna'),
  users.raw_user_meta_data ->> 'nim',
  'student',
  'active',
  users.raw_user_meta_data ->> 'avatar_url'
from auth.users users
on conflict (id) do nothing;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select case
    when coalesce(
      (select role from public.profiles where id = auth.uid()),
      'student'
    ) = 'student'
    and exists (
      select 1
      from public.anggota_kelas member
      where lower(member.user_email) =
        lower(coalesce(auth.jwt() ->> 'email', ''))
        and lower(member.role) in (
          'admin',
          'ketua kelas',
          'ketua',
          'class_leader'
        )
    )
      then 'class_leader'
    else coalesce(
      (select role from public.profiles where id = auth.uid()),
      'student'
    )
  end;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_user_role() = 'admin';
$$;

create or replace function public.delete_user_account(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  target_role text;
begin
  if public.current_user_role() <> 'admin' then
    raise exception 'Only an admin can delete user accounts';
  end if;
  if target_user_id = auth.uid() then
    raise exception 'Admin cannot delete the active account';
  end if;

  select role into target_role
  from public.profiles
  where id = target_user_id;

  if target_role is null then
    raise exception 'User account not found';
  end if;
  if target_role = 'admin' then
    raise exception 'Admin accounts cannot be deleted here';
  end if;

  delete from auth.users where id = target_user_id;
end;
$$;

create or replace function public.enforce_academic_role_rules()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  active_role text := public.current_user_role();
begin
  if tg_table_name = 'tasks' and tg_op in ('INSERT', 'UPDATE') then
    new.target_role := null;
  end if;

  if tg_table_name = 'kelas' then
    if tg_op = 'INSERT' and active_role not in ('student', 'class_leader') then
      raise exception 'Only students or class leaders can create classes';
    elsif tg_op = 'UPDATE' and not (
      active_role = 'admin'
      or old.created_by = auth.uid()
      or public.is_class_leader(old.id)
    ) then
      raise exception 'Only this class leader can update the class';
    elsif tg_op = 'DELETE' and active_role <> 'admin' then
      raise exception 'Only admins can delete classes';
    end if;
  elsif tg_table_name = 'matakuliah' then
    if tg_op = 'INSERT' and (
      active_role <> 'lecturer'
      or new.lecturer_id is distinct from auth.uid()
    ) then
      raise exception 'Only lecturers can create courses';
    elsif tg_op = 'UPDATE' and not (
      active_role = 'admin'
      or (
        active_role = 'lecturer'
        and old.lecturer_id is not distinct from auth.uid()
      )
    ) then
      raise exception 'Only the lecturer owner can update a course';
    elsif tg_op = 'DELETE' and active_role <> 'admin' then
      raise exception 'Only admins can delete courses';
    end if;
  elsif tg_table_name in ('tasks', 'jadwal_kelas') then
    if tg_op = 'INSERT' and not (
      active_role = 'admin'
      or (
        active_role in ('student', 'class_leader')
        and public.is_class_member(new.kelas_id)
      )
    ) then
      raise exception 'Only class members can create class data';
    elsif tg_op = 'UPDATE' and not (
      active_role = 'admin'
      or (
        active_role in ('student', 'class_leader')
        and public.is_class_member(old.kelas_id)
        and public.is_class_member(new.kelas_id)
      )
    ) then
      raise exception 'Only class members can update class data';
    elsif tg_op = 'DELETE' and not (
      active_role = 'admin'
      or (
        active_role in ('student', 'class_leader')
        and public.is_class_member(old.kelas_id)
      )
    ) then
      raise exception 'Only class members can delete class data';
    end if;
  elsif tg_table_name = 'announcements' then
    if tg_op = 'INSERT' and not (
      new.created_by = auth.uid()
      and (
        active_role = 'lecturer'
        or (
          active_role in ('student', 'class_leader')
          and new.target_class is not null
          and public.is_class_leader(new.target_class)
        )
      )
    ) then
      raise exception 'Role is not allowed to create this announcement';
    elsif tg_op = 'UPDATE' and not (
      old.created_by = auth.uid()
      and (
        active_role = 'lecturer'
        or (
          active_role in ('student', 'class_leader')
          and old.target_class is not null
          and new.target_class is not null
          and public.is_class_leader(old.target_class)
          and public.is_class_leader(new.target_class)
        )
      )
    ) then
      raise exception 'Only the author can update an announcement';
    elsif tg_op = 'DELETE' and not (
      active_role = 'admin'
      or (
        active_role in ('lecturer', 'student', 'class_leader')
        and old.created_by = auth.uid()
        and (
          active_role = 'lecturer'
          or (
            old.target_class is not null
            and public.is_class_leader(old.target_class)
          )
        )
      )
    ) then
      raise exception 'Role is not allowed to delete announcements';
    end if;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

create trigger enforce_class_roles
  before insert or update or delete on public.kelas
  for each row execute function public.enforce_academic_role_rules();
create trigger enforce_course_roles
  before insert or update or delete on public.matakuliah
  for each row execute function public.enforce_academic_role_rules();
create trigger enforce_task_roles
  before insert or update or delete on public.tasks
  for each row execute function public.enforce_academic_role_rules();
create trigger enforce_schedule_roles
  before insert or update or delete on public.jadwal_kelas
  for each row execute function public.enforce_academic_role_rules();

create or replace function public.enforce_schedule_leader_only()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' and not public.is_class_leader(new.kelas_id) then
    raise exception 'Only the class leader can create schedules';
  elsif tg_op = 'UPDATE' and not (
    public.is_admin()
    or (
      public.is_class_leader(old.kelas_id)
      and public.is_class_leader(new.kelas_id)
    )
  ) then
    raise exception 'Only the class leader can update schedules';
  elsif tg_op = 'DELETE' and not (
    public.is_admin()
    or public.is_class_leader(old.kelas_id)
  ) then
    raise exception 'Only the class leader can delete schedules';
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

create trigger enforce_schedule_leader_only
  before insert or update or delete on public.jadwal_kelas
  for each row execute function public.enforce_schedule_leader_only();
create trigger enforce_announcement_roles
  before insert or update or delete on public.announcements
  for each row execute function public.enforce_academic_role_rules();

create or replace function public.validate_announcement_course()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  active_role text := public.current_user_role();
begin
  if active_role = 'lecturer' then
    if new.course_id is null or not exists (
      select 1
      from public.matakuliah course
      where course.id = new.course_id
        and course.lecturer_id = auth.uid()
    ) then
      raise exception 'Lecturers must select one of their own courses';
    end if;
  elsif new.course_id is not null then
    raise exception 'Only lecturers can attach courses to announcements';
  end if;

  return new;
end;
$$;

create trigger validate_announcement_course
  before insert or update on public.announcements
  for each row execute function public.validate_announcement_course();

create or replace function public.prevent_unauthorized_role_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (
    new.role is distinct from old.role
    or new.requested_role is distinct from old.requested_role
    or new.approval_status is distinct from old.approval_status
  )
  and coalesce(auth.role(), '') <> 'service_role'
  and session_user <> 'postgres'
  and public.current_user_role() <> 'admin'
  then
    raise exception 'Only an admin can change user roles';
  end if;

  return new;
end;
$$;

create trigger protect_profile_role
  before update on public.profiles
  for each row execute function public.prevent_unauthorized_role_change();

create or replace function public.is_class_member(target_class_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.anggota_kelas member
    where member.kelas_id = target_class_id
      and lower(member.user_email) =
        lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

create or replace function public.is_class_leader(target_class_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.anggota_kelas member
    where member.kelas_id = target_class_id
      and lower(member.user_email) =
        lower(coalesce(auth.jwt() ->> 'email', ''))
      and lower(member.role) in (
        'admin',
        'ketua kelas',
        'ketua',
        'class_leader'
      )
  );
$$;

create or replace function public.can_manage_class(target_class_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.is_admin()
    or exists (
      select 1
      from public.kelas classroom
      where classroom.id = target_class_id
        and classroom.created_by = auth.uid()
    )
    or public.is_class_leader(target_class_id)
    or exists (
      select 1
      from public.matakuliah course
      where course.kelas_id = target_class_id
        and course.lecturer_id = auth.uid()
    );
$$;

create or replace function public.join_class(access_code text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  target_class public.kelas%rowtype;
  assigned_role text := 'student';
  current_email text := coalesce(auth.jwt() ->> 'email', '');
  current_profile public.profiles%rowtype;
begin
  if auth.uid() is null or trim(current_email) = '' then
    raise exception 'Authentication required';
  end if;

  select *
  into target_class
  from public.kelas classroom
  where upper(classroom.kode_kelas) = upper(trim(access_code))
     or upper(classroom.kode_wakil) = upper(trim(access_code))
  limit 1;

  if not found then
    raise exception 'Kode kelas tidak valid';
  end if;
  if not target_class.is_open then
    raise exception 'Kelas sedang ditutup';
  end if;
  if upper(target_class.kode_wakil) = upper(trim(access_code)) then
    assigned_role := 'class_leader';
  end if;

  select *
  into current_profile
  from public.profiles
  where id = auth.uid();

  insert into public.anggota_kelas (
    kelas_id,
    user_email,
    role,
    user_name,
    nim,
    avatar_url
  )
  values (
    target_class.id,
    current_email,
    assigned_role,
    coalesce(current_profile.display_name, 'Pengguna'),
    coalesce(current_profile.student_number, '-'),
    current_profile.avatar_url
  )
  on conflict do nothing;

  return target_class.id;
end;
$$;

-- RLS is intentionally disabled for this academic project.
alter table public.profiles disable row level security;
alter table public.kelas disable row level security;
alter table public.anggota_kelas disable row level security;
alter table public.matakuliah disable row level security;
alter table public.jadwal_kelas disable row level security;
alter table public.tasks disable row level security;
alter table public.announcements disable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete on table
  public.profiles,
  public.kelas,
  public.anggota_kelas,
  public.matakuliah,
  public.jadwal_kelas,
  public.tasks,
  public.announcements
to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.current_user_role() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_class_member(bigint) to authenticated;
grant execute on function public.is_class_leader(bigint) to authenticated;
grant execute on function public.can_manage_class(bigint) to authenticated;
grant execute on function public.join_class(text) to authenticated;
grant execute on function public.delete_user_account(uuid) to authenticated;

insert into storage.buckets (id, name, public)
values ('files', 'files', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists files_public_read on storage.objects;
drop policy if exists files_authenticated_insert on storage.objects;
drop policy if exists files_authenticated_update on storage.objects;
drop policy if exists files_authenticated_delete on storage.objects;
drop policy if exists files_authenticated_all on storage.objects;

create policy files_authenticated_all on storage.objects
  for all to authenticated
  using (bucket_id = 'files')
  with check (bucket_id = 'files');

do $$
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) then
    begin
      alter publication supabase_realtime
        add table public.jadwal_kelas;
    exception
      when duplicate_object then null;
    end;
  end if;
end;
$$;

commit;
